---
title: "Marzuki Nooranas." 
---
```{r, eval=TRUE,echo=FALSE}

library(grid)
library(gridExtra)
library(png)

img1 <- readPNG("images/me_icon.png")
img2 <- readPNG("images/68FD47AF-F084-4FCC-85AC-4712EEC1B685.PNG")

grid.arrange(rasterGrob(img1, width=unit(1.1,"npc"), height=unit(0.8,"npc"), gp=gpar(mai=c(0,0,0,0))), 
             rasterGrob(img2, width=unit(1,"npc"), height=unit(0.7,"npc"), gp=gpar(mai=c(0,0,0,0))), 
             ncol=2)

```

# **Well Hello There!**

Hello there! My name is Marzuki Nooranas - or you can call me *Marz!* I am currently in my 2nd year, double majoring in Sociology and, Communications and New Media! 

I have always been fascinated by how society functions and its intricate connections, my passion for understanding the world around us, is driven by a desire to foster meaningful connections within all communities! To demonstrate this, I embark of frequent backpacking trips across Southeast Asia, and actively engage myself in the cultures and learn about their customs. Such experiences provide me with firsthand insights into how different societies interact, and not only broadening my horizons, but also fostering empathy across different communities


# Link to Course Content:

### <https://github.com/mrzknrns/NM2207.git>

```{}
```
