---
title: "Challenge-9"
author: "Marzuki Nooranas"
date: '`r Sys.Date()`'
output:
  word_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Code Along - 9

## Slide 8: 

```{r, eval=TRUE,echo=TRUE}
library(tidyverse)

tidydata <- tribble(
~country, ~year, ~cases, ~population,
"Afghanistan", 1999, 745, 19987071,
"Afghanistan", 2000, 2666, 20595360,
"Brazil", 1999, 37737, 172006362,
"Brazil", 2000, 80488, 174504898,
"China", 1999, 212258, 1272915272,
"China", 2000, 213766, 1280428583)

tidydata

```

```{r, eval=TRUE,echo=TRUE}
nontidydata <- tribble(
  
~country,~year,~rate,
"Afghanistan", 1999, "745/19987071",
"Afghanistan", 2000, "2666/20595360",
"Brazil", 1999, "37737/172006362",
"Brazil", 2000, "80488/174504898",
"China", 1999, "212258/1272915272",
"China", 2000, "213766/1280428583")

nontidydata

```

## Slide 11: 
```{r, eval=TRUE,echo=TRUE}
nontidydata
```

```{r, eval=TRUE,echo=TRUE}
tidieddata <- nontidydata %>%
  separate(rate, into = c("cases",
                          "population"),
           sep = "/")
tidieddata
```


#Slide 12:
```{r, eval=TRUE,echo=TRUE}

newtidieddata <- tidieddata %>%
  pivot_longer(
    cols = cases:population,
    names_to = "measurement",
    values_to = "value"
  )
newtidieddata


```

#Slide 13:
```{r, eval=TRUE,echo=TRUE}
ggplot(newtidieddata) +
  aes(x=year,y=value, colour=country) +
  geom_point() +
  geom_line(aes(group = country))+
  facet_wrap(~measurement) +
  theme_bw()

```

#Slide 14: 
```{r, eval=TRUE,echo=TRUE}
df <- tribble(
  ~id, ~bp1, ~bp2,
  "A", 100, 120,
  "B", 140, 115,
  "C", 120, 125
)
df

```

```{r, eval=TRUE,echo=TRUE}
df %>%
  pivot_longer(
    cols = bp1:bp2,
    names_to = "measurement",
    values_to = "value"
)

```

# Slide 18:
```{r, eval=TRUE,echo=TRUE}
newtidieddata

```

```{r, eval=TRUE,echo=TRUE}

newtidieddata %>%
  pivot_wider(names_from="measurement",
              values_from="value")
```


#Slide 19: 
```{r, eval=TRUE,echo=TRUE}
df <- tribble(
  ~id, ~measurement, ~value,
  "A", "bp1", 100,
  "B", "bp1", 140,
  "B", "bp2", 115,
  "A", "bp2", 120,
  "A", "bp3", 105
)
df

```

```{r, eval=TRUE,echo=TRUE}
df %>%
  pivot_wider(
    names_from = measurement,
    values_from = value
)

```

## Challenge 9 Question 1:

```{r, eval=TRUE,echo=TRUE}
billboard  


billboard_new <- billboard %>%
  pivot_longer(cols = starts_with("wk"),
               names_to = "week",
               values_to = "rank",
               values_drop_na = TRUE) %>%
  mutate(week = parse_number(week))

ggplot(billboard_new, aes(x = week, y = rank)) +
  geom_line(alpha = 0.7) + 
  labs(title = "Song Ranks Over Weeks", 
       x = "Week", 
       y = "Rank") +
  theme_minimal()

```

## Challenge 9 Question 2:

```{r, eval=TRUE,echo=TRUE}

cms_patient_experience


cms_wider <- cms_patient_experience %>%
  pivot_wider(names_from = measure_cd,
              values_from = prf_rate,
              id_cols = starts_with("org"))

head(cms_wider)

```

